version: '3'

services:

  django:
    restart: always
    build: ./django
    # map the local (host) directories to their container counterparts
    # to support live-syncing
    volumes:
      - ./django/sampleproj:/app/django/sampleproj
      - ./django/api:/app/django/api
    ports:
      - "8000:8000"
    command: bash -c "python manage.py migrate --settings=sampleproj.settings.local && python manage.py runserver 0.0.0.0:8000 --settings=sampleproj.settings.local"

  react:
    build: ./boilerplate-ts
    volumes:
      - ./boilerplate-ts:/app/boilerplate-ts
      - /app/boilerplate-ts/node_modules
    ports:
      - "3000:3000"
    command: ["npm", "start"]
